"""add client_type to application

Revision ID: efc5e98f7dfa
Revises: 
Create Date: 2026-04-13 18:46:40.343581

"""
from typing import Sequence, Union
import sys
from pathlib import Path

from alembic import op
import sqlalchemy as sa

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from helpers import column_exists  # noqa: E402


# revision identifiers, used by Alembic.
revision: str = 'efc5e98f7dfa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    if not column_exists("application", "client_type"):
        with op.batch_alter_table("application", schema=None) as batch_op:
            batch_op.add_column(
                sa.Column(
                    "client_type",
                    sa.String(length=20),
                    server_default="confidential",
                    nullable=False,
                    comment="客户端类型：confidential / public",
                )
            )

    if not column_exists("authorization_code", "code_challenge"):
        with op.batch_alter_table("authorization_code", schema=None) as batch_op:
            batch_op.add_column(
                sa.Column(
                    "code_challenge",
                    sa.String(length=255),
                    nullable=True,
                    comment="PKCE code_challenge",
                )
            )
    if not column_exists("authorization_code", "code_challenge_method"):
        with op.batch_alter_table("authorization_code", schema=None) as batch_op:
            batch_op.add_column(
                sa.Column(
                    "code_challenge_method",
                    sa.String(length=20),
                    nullable=True,
                    comment="PKCE code_challenge_method",
                )
            )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authorization_code', schema=None) as batch_op:
        batch_op.drop_column('code_challenge_method')
        batch_op.drop_column('code_challenge')

    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.drop_column('client_type')

    # ### end Alembic commands ###
